### ISSUE TITLE
 广汽丰田报错了

### ISSUE THREAD

**Issue by kk1906** [smallfawn/QLScriptPublic#1]

**Comment by smallfawn** [comment]
好的了解到，下周更新

**Comment by smallfawn** [comment]
可以告诉我哪里报错了嘛

**Comment by kk1906** [comment]
🔔广汽丰田, 开始!
共找到1个账号
================== 签到 ==================

post请求失败

❗️广汽丰田, 错误!

TypeError: Cannot read properties of undefined (reading 'header')
    at UserInfo.task_signin 
开始点赞
post请求失败

❗️广汽丰田, 错误!

TypeError: Cannot read properties of undefined (reading 'header')
    at UserInfo.task_lik
账号[1]  文章列表[1662425493103689729]
开始浏览

post请求失败

❗️广汽丰田, 错误!

**Comment by kk1906** [comment]
网址变了

**Comment by smallfawn** [comment]
加密方式变了 正在修

**Comment by smallfawn** [comment]
已经修复
