### ISSUE TITLE
「求本」微信小程序～点码广告

### ISSUE THREAD

**Issue by z271491022** [smallfawn/QLScriptPublic#102]
![D7395B0D-CE38-415C-89EA-3304ED2E6B68](https://github.com/smallfawn/QLScriptPublic/assets/106092070/2893f2b6-6b8d-4dfd-ac3a-7731ac30ba3e)
![C4793130-E39C-496E-8FAD-70613C5D5FB7](https://github.com/smallfawn/QLScriptPublic/assets/106092070/0ad055f3-8c8c-4ba6-a4cb-3cc6a56adfa4)
![10BF3F3F-7FD3-4F43-B840-095814297BB5](https://github.com/smallfawn/QLScriptPublic/assets/106092070/4b0c8b9f-2df8-4df2-8916-2ab9db05de80)
每日收益2块钱3块的样子，求大佬写个本

**Comment by smallfawn** [comment]
收到
