### ISSUE TITLE
可口可乐

### ISSUE THREAD

**Issue by lihongyuan99** [smallfawn/QLScriptPublic#107]
可口可乐是不是寄了

**Comment by 3238614968** [comment]
啊？具体哪个？

**Comment by lihongyuan99** [comment]
[Coca.py](https://github.com/smallfawn/QLScriptPublic/blob/main/Coca.py)可口可乐吧签到运行报错

**Comment by 3238614968** [comment]
🆗

**Comment by 5jwoj** [comment]
## 开始执行... 2023-10-17 16:41:57

⚠️⚠️⚠️脚本报错执行下一个账号⚠️⚠️⚠️


## 执行结束... 2023-10-17 16:41:58  耗时 1 秒
