### ISSUE TITLE
永璞小岛小程序签到

### ISSUE THREAD

**Issue by lihongyuan99** [smallfawn/QLScriptPublic#117]
签到兑换周边（马克杯等），token通过这个请求刷新，请求体带了个code，但是怎么都找不到这个code哪来的，求大佬指点迷津
![IMG_6314](https://github.com/smallfawn/QLScriptPublic/assets/64824864/1661a67c-855e-4105-9efd-db557e8c79c8)

**Comment by lihongyuan99** [comment]
![IMG_6312](https://github.com/smallfawn/QLScriptPublic/assets/64824864/48b83bf7-e90a-45c6-82f1-6fc39f63ff8c)

**Comment by smallfawn** [comment]
刷新

**Comment by Huansheng1** [comment]
code微信授权来的，没救
