### ISSUE TITLE
投稿：托迈酷客小程序每日签到可获得积分，年终奖

### ISSUE THREAD

**Issue by niceqishi** [smallfawn/QLScriptPublic#118]
原脚本只能圈叉，大佬看看可以到青龙中吗：(https://github.com/FoKit/Scripts/blob/main/scripts/ThomasCook.js)

**Comment by 3238614968** [comment]
😅

**Comment by 3238614968** [comment]
![image](https://github.com/smallfawn/QLScriptPublic/assets/88702174/7cea0a59-7600-4a13-a0e2-3e87b238203d)
na'g哪个？

**Comment by 3238614968** [comment]
> > 你这个不就是成品吗
> > 原来是青龙版本太低。。。升级就好了😅

正常喽？

**Comment by niceqishi** [comment]
> > > 你这个不就是成品吗
> > > 原来是青龙版本太低。。。升级就好了😅
> 
> 正常喽？

正常了 据说ck有效期很久
