### ISSUE TITLE
美的会员小程序也可以搞搞

### ISSUE THREAD

**Issue by xfmeng970526** [smallfawn/QLScriptPublic#127]
美的会员小程序也可以搞搞

**Comment by gigi2u** [comment]
微信小程序 - 美的会员,开始!
加载sendNotify，当前版本: 20230712
共找到1个账号
❌签到失败
"{\r\n\"errCode\" : 314,\r\n\"errcode\" : 314,\r\n\"errMsg\" : \"errno:0000013A \nFrame:00 :--FILE:j_util.go LN:663 FUNC:makeErrorMsg  err:IOT return error code:314, msg :积分领取次数超过规则设定次数\",\r\n\"errmsg\" : \"errno:0000013A \nFrame:00 :--FILE:j_util.go LN:663 FUNC:makeErrorMsg  err:IOT return error code:314, msg :积分领取次数超过规则设定次数\"\r\n}\r\n"
