### ISSUE TITLE
传祺出2.0版本了

### ISSUE THREAD

**Issue by linxuanning** [smallfawn/QLScriptPublic#128]

**Comment by kk1906** [comment]
确实都解封了

**Comment by smallfawn** [comment]
正在写

**Comment by hlxsheng** [comment]
大佬加油

**Comment by smallfawn** [comment]
出炉了

**Comment by hetoo** [comment]
> 出炉了

大佬，评论能否也删除掉？

**Comment by smallfawn** [comment]
正在考虑，评论加个开关就没什么豆了

**Comment by hetoo** [comment]
> 正在考虑，评论加个开关就没什么豆了

可以评论，就是和发文章一样，发布后再删除

**Comment by smallfawn** [comment]
弄了

**Comment by hetoo** [comment]
大佬，可以再提一个小建议不
有时候为了防止执行失败，一天需要设置脚本执行两次
像签到 发帖 评论 分享都是执行一次，设置了抽奖默认一次，如果已经执行过了，是否下次不再执行
防止重复操作，引起封号

**Comment by smallfawn** [comment]
加了 刚加  更新吧

**Comment by hetoo** [comment]
> 加了 刚加 更新吧

点个赞，速度真快

**Comment by hetoo** [comment]
最新脚本，貌似评论没有执行
日志如下：

> 默认抽奖次数1
> 抽奖次数剩余10次
> 抽奖成功获得[3G豆]
> 当前G豆数量[****]
> 已经连续签到4天
> 签到[success]
> 正在远程获取15条随机评论~请等待15-20秒
> 已设置发帖功能
> 发表文章[success]
> 等待30s
> 删除文章[success]
> 转发[success]
> 已设置评论功能
> 11/26截止 Do - 广州车展活动 奖品活动结束后14日内发放
> 抽奖成功获得[谢谢参与]
> 已设置开启每日助力
> 添加助力任务成功
> 助力ID获取成功********
> 已经分享成功
> 助力执行成功 可能助力失败 正常情况
> 已填写微信广汽传祺Token 执行答题&抽奖
> 本周答题完成或未到活动时间
