### ISSUE TITLE
美的会员小程序多账号第二个账号开始提示登录失败

### ISSUE THREAD

**Issue by SeanSuny** [smallfawn/QLScriptPublic#131]
![screenshot-20231121-152609](https://github.com/smallfawn/QLScriptPublic/assets/20199755/df8c2295-8a0b-44f6-84a7-5c1ef665568d)
单账号测试没有问题

**Comment by smallfawn** [comment]
是这样的，没办法解决，不知道哪里出了问题

**Comment by moliyadi007** [comment]
async function start() {
    const tasks = userList.map(user => user.main());
    await Promise.all(tasks);
}，改成这样就好了
