### ISSUE TITLE
华润通、一点万象app签到

### ISSUE THREAD

**Issue by ghedu** [smallfawn/QLScriptPublic#134]
华润通app,一点万象app，ole lifestyle 签到积分兑换实物，这几个app积分互通

**Comment by smallfawn** [comment]
好的

**Comment by smallfawn** [comment]
能否提供抓包数据？

**Comment by ghedu** [comment]
一点万象
[Stream 抓包记录 - app.mixcapp.com.txt](https://github.com/smallfawn/QLScriptPublic/files/13455081/Stream.-.app.mixcapp.com.txt)

华润通（https://cloud.huaruntong.cn/web/online/?mFrom=fastLogin&mFrom=quickRegister#/signIn?utm_source=hrt&utm_medium=flzx&utm_content=qd0228&utm_campaign=qd0228&inviteCode=2e7cbec65eb14497bae6d29103c000f6）
[Stream 抓包记录 - mid.huaruntong.cn.txt](https://github.com/smallfawn/QLScriptPublic/files/13455083/Stream.-.mid.huaruntong.cn.txt)
 OLE LIFE
[OLE.zip](https://github.com/smallfawn/QLScriptPublic/files/13455119/OLE.zip)

**Comment by smallfawn** [comment]
华润通按打不开啊，还有你那个万象 ..........
