### ISSUE TITLE
广汽传祺CK怎么怎么快就失效了呢？

### ISSUE THREAD

**Issue by maech01** [smallfawn/QLScriptPublic#139]

**Comment by smallfawn** [comment]
你用什么获取的

**Comment by maech01** [comment]
app

**Comment by maech01** [comment]
20号到今天应该8天失效.抓包累人啊

**Comment by smallfawn** [comment]
可以试试woolweb获取呢，加我交流群，公告里面有

**Comment by maech01** [comment]
APP不掉，CK变了

**Comment by maech01** [comment]
你的还没有掉吗？

**Comment by smallfawn** [comment]
估计是刷新ck了，请提供刷新的请求发我

**Comment by maech01** [comment]
❌信息查询状态[登录已过期，请重新登录]
{"data":null,"exceptCauseApp":"trumpchi-boot-app-app","exceptCauseIp":"10.28.64.66","exceptClass":"com.dtyunxi.lang.BizRuntimeException","exceptStackTrace":null,"exportDataQueryBeanName":null,"extFields":{},"importDataHandlerBeanName":null,"resultCode":"E4000022","resultMsg":"登录已过期，请重新登录","sign":null}
执行答题&抽奖 并且尝试获取mallToken(如果不是WoolWeb获取的变量 可能执行失败)
获取问题和选项失败
{"code":"30004","msg":"授权认证失败,请重新登录","success":false}
本周答题完成或未到活动时间

**Comment by smallfawn** [comment]
请提供刷新的请求发我，应该是第七天开始打开app抓包里面就有了

**Comment by maech01** [comment]
> 请提供刷新的请求发我，应该是第七天开始打开app抓包里面就有了

听不懂啊？！

**Comment by maech01** [comment]
是重新抓包的请求？

**Comment by smallfawn** [comment]
没事了 我自己抓包吧

**Comment by smallfawn** [comment]
可以尝试用WOOLWEB获取变量呢  这个变量时间挺长的

**Comment by maech01** [comment]
app抓包7天过期

**Comment by smallfawn** [comment]
对啊怎么了，你抓refreshtoken填到本里啊

**Comment by maech01** [comment]
> 对啊怎么了，你抓refreshtoken填到本里啊

app抓refreshtoken了也还是7天过期

**Comment by smallfawn** [comment]
填了就会刷新，...我猜你没填...

**Comment by maech01** [comment]
> 填了就会刷新，...我猜你没填...

❌信息查询状态[登录已过期，请重新登录]
{"data":null,"exceptCauseApp":"trumpchi-boot-app-app","exceptCauseIp":"10.28.7.98","exceptClass":"com.dtyunxi.lang.BizRuntimeException","exceptStackTrace":null,"exportDataQueryBeanName":null,"extFields":{},"importDataHandlerBeanName":null,"resultCode":"E4000022","resultMsg":"登录已过期，请重新登录","sign":null}
尝试刷新TOKEN
重置accessToken [AT-171709-w5eUbQfeAejweSNpQAHaCdaYNaW2nI6fR0K] 重置refeshToken [RT-171709-4HkNjxjb64WuGON4GqHaxdL6aGVbVCuvAYf]
❌抽奖次数查询状态[AT已过期，请重新获取最新的AT]
{"data":null,"exceptCauseApp":"trumpchi-boot-app-activity","exceptCauseIp":"10.28.3.169","exceptClass":"com.dtyunxi.lang.BizRuntimeException","exceptStackTrace":null,"exportDataQueryBeanName":null,"extFields":{},"importDataHandlerBeanName":null,"resultCode":"E4000021","resultMsg":"AT已过期，请重新获取最新的AT","sign":null}
❌G豆查询状态[登录已过期，请重新登录]

**Comment by smallfawn** [comment]
你没写refreshtoken吧

**Comment by smallfawn** [comment]
应该是刷新了，然后没写入青龙，然后没有重新读取ck，我看看能不能改

**Comment by smallfawn** [comment]
可以了

**Comment by maech01** [comment]
> 可以了

好的
