### ISSUE TITLE
北汽不知道为什么会这样子 用这个之前的脚本可以使用

### ISSUE THREAD

**Issue by lichengfeng123** [smallfawn/QLScriptPublic#153]
## 开始执行... 2023-12-20 16:51:31

/ql/data/scripts/bjev.js:93
        let params = url.split('?')[1].split('&').sort().join("").toLowerCase()
            ^

SyntaxError: Identifier 'params' has already been declared
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.18.2

## 执行结束... 2023-12-20 16:51:32  耗时 1 秒

**Comment by smallfawn** [comment]
看代码发现你的代码未知和我最新不一致

**Comment by lichengfeng123** [comment]
你好 北汽这个没问了
丰田bz这个日志如下
🔔广汽丰田, 开始! 共找到1个账号 TypeError: Cannot read properties of undefined (reading 'match')     at _0xfa605f (/ql/data/scripts/gqft.js:20:103955)     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)     at async _0x10d630 (/ql/data/scripts/gqft.js:20:51233)     at async /ql/data/scripts/gqft.js:20:93108 🔔广汽丰田, 结束! 🕛 3.96 秒 ## 执行结束... 2023-12-21 17:05:12  耗时 5 秒　　　




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "smallfawn/QLScriptPublic"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月20日(星期三) 下午4:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [smallfawn/QLScriptPublic] 北汽不知道为什么会这样子 用这个之前的脚本可以使用 (Issue #153)





 
看代码发现你的代码未知和我最新不一致
