### ISSUE TITLE
乐活app

### ISSUE THREAD

**Issue by Huansheng1** [smallfawn/QLScriptPublic#17]
![image](https://github.com/smallfawn/QLScriptPublic/assets/33859558/86d96447-716c-46b8-b28e-cfd7c4324344)

**Comment by smallfawn** [comment]
收到，这周更新

**Comment by smallfawn** [comment]
用的是中青看点的加密，有点难搞，计划延后

**Comment by paozhe** [comment]
<img width="576" alt="看岱山" src="https://github.com/smallfawn/QLScriptPublic/assets/136290698/09f7f367-75f2-4204-9491-c572bbb685d0">
