### ISSUE TITLE
中健365.py 只能识别一个账号

### ISSUE THREAD

**Issue by CC13594759** [smallfawn/QLScriptPublic#18]
中健365.py 只能识别一个账号  换行多账号直接乱码不能运行

**Comment by loren-loren** [comment]
中健365.py 运行提示报错
## 开始执行... 2023-07-25 11:55:25

timeout: the monitored command dumped core

## 执行结束... 2023-07-25 11:55:27 耗时 2 秒

**Comment by Huansheng1** [comment]
@241793
