### ISSUE TITLE
爱嵊州无效

### ISSUE THREAD

**Issue by zhzGitHub123** [smallfawn/QLScriptPublic#19]
我使用的是x-session-id,期间没有任何报错，但是脚本结束后积分并没有任何变动，进去app查看任务也都没完成，手动做任务倒是没问题

**Comment by Huansheng1** [comment]
爱嵊州不加任务暂时没有解决办法，原因不明，等大佬提供解决方案

**Comment by big-tooth** [comment]
> 我使用的是x-session-id,期间没有任何报错，但是脚本结束后积分并没有任何变动，进去app查看任务也都没完成，手动做任务倒是没问题

应该是需要获取`artlistdata`字段

**Comment by Huansheng1** [comment]
> > 我使用的是x-session-id,期间没有任何报错，但是脚本结束后积分并没有任何变动，进去app查看任务也都没完成，手动做任务倒是没问题
> 
> 应该是需要获取`artlistdata`字段

artlistdata我是写了的，“爱嵊州”我已经登录不进去了，登录或者注册都提示：当前操作不允许 或 被阻止，故之前已经停更并删除该脚本【更换设备、手机号、IP皆试过】

**Comment by big-tooth** [comment]
> > > 我使用的是x-session-id,期间没有任何报错，但是脚本结束后积分并没有任何变动，进去app查看任务也都没完成，手动做任务倒是没问题
> > 
> > 
> > 应该是需要获取`artlistdata`字段
> 
> artlistdata我是写了的，“爱嵊州”我已经登录不进去了，登录或者注册都提示：当前操作不允许 或 被阻止，故之前已经停更并删除该脚本【更换设备、手机号、IP皆试过】

我已经登进去了，但是无法完成部分任务`{"code":30000,"message":"用户认证失败，请重新登录【AuthorityError:第三方系统返回异常（“+postResult+”）(10002)】"}`
