### ISSUE TITLE
大佬，天之葵商城签到

### ISSUE THREAD

**Issue by ailin98** [smallfawn/QLScriptPublic#21]

**Comment by smallfawn** [comment]
收到

**Comment by Huansheng1** [comment]
![image](https://github.com/smallfawn/QLScriptPublic/assets/33859558/0bad664a-f5c7-45ca-94c1-34c16483c8fb)

**Comment by ailin98** [comment]
![image](https://github.com/smallfawn/QLScriptPublic/assets/43498502/24758082-59ba-4800-b2ee-ea0b38d8546f)
只是推荐奖励没了，签到还有的大佬

**Comment by ailin98** [comment]
> ![图像](https://user-images.githubusercontent.com/33859558/256841727-0bad664a-f5c7-45ca-94c1-34c16483c8fb.png)

签到奖励还有，推荐奖励没了，大佬
