### ISSUE TITLE
望潮跑不了什么情况

### ISSUE THREAD

**Issue by a1564471347** [smallfawn/QLScriptPublic#22]
![Uploading IMG_2804.jpeg…]()

**Comment by a1564471347** [comment]
![Uploading IMG_2804.jpeg…]()

**Comment by smallfawn** [comment]
亲，可以跑的，跑不了建议使用账号密码版或变量版，还是不行可以换一个IP，或者找其他人帮你挂

**Comment by Huansheng1** [comment]
你贴的图片有问题，无法访问，请检查自己的运行环境，望潮不支持 部分服务器IP以及手机面具青龙

**Comment by a1564471347** [comment]
> 你贴的图片有问题，无法访问，请检查自己的运行环境，望潮不支持 部分服务器IP以及手机面具青龙

登录异常HTTPSConnectionPool(host='xmt.taizhou.com.cn', port=443): Max retries exceeded with url: /prod-api/user-read/app/login?id=64c10a2e3f293a40c8be9eaf&sessionId=64c1f2bb6ab0c85782affc04 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f5c57349180>: Failed to resolve 'xmt.taizhou.com.cn' ([Errno -3] Try again)"))服务器甲骨文春川青龙

**Comment by smallfawn** [comment]
可以跑

**Comment by a1564471347** [comment]
> 可以跑

现在用望潮抽奖这个吗？wangchao.js这个以后不用了吗
