### ISSUE TITLE
各种账号密码版的 全503了

### ISSUE THREAD

**Issue by CC13594759** [smallfawn/QLScriptPublic#23]
![image](https://github.com/smallfawn/QLScriptPublic/assets/59593391/8701edc9-886f-43d2-99da-0a0ceeeae83a)
南湖声音-掌上鹿城-诗画浦江-仑传-掌上温岭-今日越城-掌上瓯海-爱海盐-

**Comment by faintout** [comment]
等更新把

**Comment by Huansheng1** [comment]
好的，这两天更新

**Comment by Huansheng1** [comment]
今日越城-掌上瓯海-爱海盐 已更新，其他的貌似不是我写的，先加了个 仑传

**Comment by Huansheng1** [comment]
能更的已经更了，经测试部分提到的app没有可换东西，不搞
![image](https://github.com/smallfawn/QLScriptPublic/assets/33859558/6c505bf0-989e-4fba-8747-f1c1e37b529f)
