### ISSUE TITLE
读嘉完成任务失败

### ISSUE THREAD

**Issue by faintout** [smallfawn/QLScriptPublic#26]
✅账号[1]  该文章已阅读🎉
✅账号[1]  该文章已阅读🎉
❌账号[1]  完成任务失败
{
  url: 'https://yapi.y-h5.iyunxh.com/api/aosbasemodule/task_done',
  headers: {
    Host: 'yapi.y-h5.iyunxh.com',
    Connection: 'keep-alive',
    'Access-User-Id': '13309541',
    'Access-Api-Signature': 'jiaxing;t3ftKD6E8QrtxXe75Mz48MbaCiJHkH4r;1690520144249;e459bfae3fcd71a90f8f9276a304bc53',
    'Access-T-Id-In': '41',
    'Access-Wxclient-Type': 'wx_app',
    'User-Agent': 'Mozilla/5.0 (Linux; Android 10; MI 8 Lite Build/QKQ1.190910.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/81.0.4044.138 Mobile Safari/537.36;xsb_dujia;xsb_dujia;8.0.4;native_app',
    'Access-Token': 'b39701bc60ef7a65c27d15d3382baf05ZXhwPTE3MDA1MTg3MzImaWF0PTE2OTA1MTg3MzImbmJmPTE2NjY5NDM4NTUmanRpPXBYdjZMQiZkYXRhJTVCdF9pZCU1RD00MSZkYXRhJTVCdF9pZF9pbiU1RD00MSZkYXRhJTVCdXNlcl9pZCU1RD0xMzQzMjk4NSZkYXRhJTVCdXNlcl9uYW1lJTVEPSVFOCVBRiVCQiVFNSU4RiU4Ql9IU1VQOVkmZGF0YSU1Qm5hbWUlNUQ9JUU4JUFGJUJCJUU1JThGJThCX0hTVVA5WQ==',
    'Access-Api-Unique-Token': '1',
    'Content-Type': 'application/json',
    'Access-Api-Dt': '0714b53006bcffccecc3cc52dbde8f49b8ff',
    'Access-T-Id': '41',
    Accept: '*/*',
    Origin: 'https://jiaxing.y-h5.iyunxh.com',
    'X-Requested-With': 'com.hoge.android.app.hdd',
    'Sec-Fetch-Site': 'same-site',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Dest': 'empty',
    Referer: 'https://jiaxing.y-h5.iyunxh.com/module-study/pass-detail/pass-detail?pass_id=1147&activity_id=140',
    'Accept-Encoding': 'gzip, deflate',
    'Accept-Language': 'zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7'
  },
  body: '{"task_record_id":13411737,"collect_info":"","afs_tokenid":"4ee9eceb42ced70275466c458cdd3f34","device_token":"1690516635919295663"}',
  cookieJar: CookieJar {
    rejectPublicSuffixes: true,
    enableLooseMode: false,
    allowSpecialUseDomain: true,
    store: { idx: [Object: null prototype] {} },
    prefixSecurity: 'silent',
    _cloneSync: [Function (anonymous)],
    _importCookiesSync: [Function (anonymous)],
    getCookiesSync: [Function (anonymous)],
    getCookieStringSync: [Function (anonymous)],
    getSetCookieStringsSync: [Function (anonymous)],
    removeAllCookiesSync: [Function (anonymous)],
    setCookieSync: [Function (anonymous)],
    serializeSync: [Function (anonymous)]
  }
}
{ code: '1003', msg: '缺少参数或者参数异常', data: [] }

已阅读的正常，没阅读过的显示异常

**Comment by smallfawn** [comment]
读嘉有BUG

**Comment by smallfawn** [comment]
修复了
