### ISSUE TITLE
望潮抽奖js报错：账号不存在

### ISSUE THREAD

**Issue by Cyber-H** [smallfawn/QLScriptPublic#28]
<img width="479" alt="image" src="https://github.com/smallfawn/QLScriptPublic/assets/45815405/75413d87-75d6-4f98-bd7c-98ea35759a3e">

**Comment by smallfawn** [comment]
请看下注释

**Comment by a1564471347** [comment]
> 请看下注释

我也是，应该脚本有点问题识别不了cookie

**Comment by smallfawn** [comment]
你写的是什么变量

**Comment by Huansheng1** [comment]
> > 请看下注释
> 
> 我也是，应该脚本有点问题识别不了cookie

望潮抽奖.js的配置是 手机号&密码
wangchao.js的配置是 X-ACCOUNT-ID&X-SESSIONID
请检查喔

**Comment by Cyber-H** [comment]
今晚更新的版本可以了。

**Comment by a1564471347** [comment]
> > > 请看下注释
> > 
> > 
> > 我也是，应该脚本有点问题识别不了cookie
> 
> 望潮抽奖.js的配置是 手机号&密码 wangchao.js的配置是 X-ACCOUNT-ID&X-SESSIONID 请检查喔
![Uploading IMG_2841.jpeg…]()

**Comment by a1564471347** [comment]
> > > 请看下注释
> > 
> > 
> > 我也是，应该脚本有点问题识别不了cookie
> 
> 望潮抽奖.js的配置是 手机号&密码 wangchao.js的配置是 X-ACCOUNT-ID&X-SESSIONID 请检查喔

![Uploading IMG_2841.jpeg…]()

**Comment by a1564471347** [comment]
> > > 请看下注释
> > 
> > 
> > 我也是，应该脚本有点问题识别不了cookie
> 
> 望潮抽奖.js的配置是 手机号&密码 wangchao.js的配置是 X-ACCOUNT-ID&X-SESSIONID 请检查喔

望潮, 错误!
TypeError: Cannot read properties of undefined (reading 'headers')
    at /ql/data/scripts/raw_main_wangchao.js:13:8579
    at Object.ONyfa (/ql/data/scripts/raw_main_wangchao.js:13:152211)
    at /ql/data/scripts/raw_main_wangchao.js:13:193385
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)这是什么原因

**Comment by Huansheng1** [comment]
> > > > 请看下注释
> > > 
> > > 
> > > 我也是，应该脚本有点问题识别不了cookie
> > 
> > 
> > 望潮抽奖.js的配置是 手机号&密码 wangchao.js的配置是 X-ACCOUNT-ID&X-SESSIONID 请检查喔
> 
> 望潮, 错误! TypeError: Cannot read properties of undefined (reading 'headers') at /ql/data/scripts/raw_main_wangchao.js:13:8579 at Object.ONyfa (/ql/data/scripts/raw_main_wangchao.js:13:152211) at /ql/data/scripts/raw_main_wangchao.js:13:193385 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)这是什么原因

[https://github.com/smallfawn/QLScriptPublic/issues/22](https://github.com/smallfawn/QLScriptPublic/issues/22)
