### ISSUE TITLE
不知道缺啥东西 大佬给看一下

### ISSUE THREAD

**Issue by kkkkxl** [smallfawn/QLScriptPublic#29]
![1690602991951](https://github.com/smallfawn/QLScriptPublic/assets/37541028/a1826679-bc1f-4bcc-ac19-d6aac49ef821)

**Comment by kkkkxl** [comment]
utils文件库里面的

**Comment by smallfawn** [comment]
jsencrypt nodejs模块

**Comment by kkkkxl** [comment]
> jsencrypt nodejs模块

ok

**Comment by kkkkxl** [comment]
> jsencrypt
![1690604327449](https://github.com/smallfawn/QLScriptPublic/assets/37541028/37b5645a-341c-4d0f-9bac-7a8c7f20b525)
是版本不对吗

**Comment by kkkkxl** [comment]
还是那个错误

**Comment by smallfawn** [comment]
联系脚本作者试试吧 幻生

**Comment by kkkkxl** [comment]
> 联系脚本作者试试吧 幻生

### 好了  解决了 谢谢大佬 装了最新版本的依赖
