### ISSUE TITLE
大佬，爱看发生错误

### ISSUE THREAD

**Issue by ailin98** [smallfawn/QLScriptPublic#30]
![image](https://github.com/smallfawn/QLScriptPublic/assets/43498502/4e75b38e-6213-48d9-9db5-0ba0b8892eed)

**Comment by smallfawn** [comment]
日志可以全部发过来看看

**Comment by ailin98** [comment]
![微信截图_20230730104307](https://github.com/smallfawn/QLScriptPublic/assets/43498502/41c11c03-ef5e-4cac-b2de-c3c614b0b8d3)
大佬刚刚你更新的，出现了这错误

**Comment by smallfawn** [comment]
你写错CK了吧
