### ISSUE TITLE
读嘉的提现希望是可选的，手机没root抓不了微信包，不知道能否把奖品的跳转链接提取出来，我用电脑试试

### ISSUE THREAD

**Issue by Huansheng1** [smallfawn/QLScriptPublic#32]
不行的话，四个参数就纯手动提现就行

此外我在没填写提现的情况下，阅读没有抽奖次数，阅读十次就有抽奖机会了， 不需要阅读20下
![image](https://github.com/smallfawn/QLScriptPublic/assets/33859558/313707b6-8f35-49d1-a991-b516ee93737a)

**Comment by smallfawn** [comment]
脚本是每次阅读都会判断有没有红包弹窗，所有基本上用不到20次
