### ISSUE TITLE
是否可以在脚本保留让人自行更改UA的代码或者变量呢？

### ISSUE THREAD

**Issue by kiyochen** [smallfawn/QLScriptPublic#34]
是否可以在脚本保留让人自行更改UA的代码或者变量呢？
这样可以有效降低黑号风险。

**Comment by smallfawn** [comment]
有这个变量

**Comment by kiyochen** [comment]
> 有这个变量

没有呀。很多脚本都是加密的，改不了这个变量。比如“阅龙湾”，环境变量只填账号#密码，没有UA的环境变量名呀，想直接在脚本里改，脚本又是加密的也改不了喔

**Comment by Huansheng1** [comment]
好的，可以看备注todoList，在后续支持计划里
