### ISSUE TITLE
读嘉打卡失败，阅读文章正常

### ISSUE THREAD

**Issue by songyongguo1987** [smallfawn/QLScriptPublic#43]
--- 第[1]个账号 ---
✅账号[1]  执行打卡
❌账号[1]  获得奖励失败
{
  url: 'https://yapi.y-h5.iyunxh.com/api/aossignin/ac_sub',
  headers: {
    Host: 'yapi.y-h5.iyunxh.com',
    Connection: 'keep-alive',
    'Access-User-Id': '13442480',
    'Access-Api-Signature': 'jiaxing;RPkfxY5tW673RiS56hYBdtbn4dKbm5YP;1690854823252;c243a9b266249eb07689b0dd8e445f72',
    'Access-T-Id-In': '41',
    'Access-Wxclient-Type': 'wx_app',
    'User-Agent': 'Mozilla/5.0 (Linux; Android 10; MI 8 Lite Build/QKQ1.190910.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/81.0.4044.138 Mobile Safari/537.36;xsb_dujia;xsb_dujia;8.0.4;native_app',
    'Access-Token': '6fcd302da62337392bad500b3e4f8123ZXhwPTE3MDA2ODQzMjQmaWF0PTE2OTA2ODQzMjQmbmJmPTE2NjY5NDM4NTUmanRpPVFsTlJGWSZkYXRhJTVCdF9pZCU1RD00MSZkYXRhJTVCdF9pZF9pbiU1RD00MSZkYXRhJTVCdXNlcl9pZCU1RD0xMzQ0MjQ4MCZkYXRhJTVCdXNlcl9uYW1lJTVEPSVFOCVBRiVCQiVFNSU4RiU4Ql9IWENIOTgmZGF0YSU1Qm5hbWUlNUQ9JUU4JUFGJUJCJUU1JThGJThCX0hYQ0g5OA==',
    'Access-Api-Unique-Token': '1',
    'Content-Type': 'application/json',
    'Access-Api-Dt': '0727b53006bcffccecc3cc52dbde8f49b8ff',
    'Access-T-Id': '41',
    Accept: '*/*',
    Origin: 'https://jiaxing.y-h5.iyunxh.com',
    'X-Requested-With': 'com.hoge.android.app.hdd',
    'Sec-Fetch-Site': 'same-site',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Dest': 'empty',
    Referer: 'https://jiaxing.y-h5.iyunxh.com/module-study/pass-detail/pass-detail?pass_id=1147&activity_id=140',
    'Accept-Encoding': 'gzip, deflate',
    'Accept-Language': 'zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7'
  },
  body: '{"id":51,"collect_info":""}',
  cookieJar: CookieJar {
    rejectPublicSuffixes: true,
    enableLooseMode: false,
    allowSpecialUseDomain: false,
    store: { idx: {} },
    prefixSecurity: 'silent',
    _cloneSync: [Function (anonymous)],
    _importCookiesSync: [Function (anonymous)],
    getCookiesSync: [Function (anonymous)],
    getCookieStringSync: [Function (anonymous)],
    getSetCookieStringsSync: [Function (anonymous)],
    removeAllCookiesSync: [Function (anonymous)],
    setCookieSync: [Function (anonymous)],
    serializeSync: [Function (anonymous)]
  }
}
{ code: '1007', msg: '活动已结束', data: [] }

**Comment by smallfawn** [comment]
活动已结束

**Comment by faintout** [comment]
脚本显示已阅读，实际未阅读

**Comment by yhmcat** [comment]
> 活动已结束

8.1活动还在，刚领完3毛

**Comment by songyongguo1987** [comment]
自动低保无效，只能手动了
