### ISSUE TITLE
按zqkdFast_read.js写的抓包抓的token，居然有的无效，该怎么抓？

### ISSUE THREAD

**Issue by songyongguo1987** [smallfawn/QLScriptPublic#47]
## 开始执行... 2023-08-02 10:56:11

🔔中青极速版每日奖励, 开始!
运行正常

2022.01.09 1:51 更新版本

共找到1个CK
====================

用户[1040761334]打开极速版失败：token无效

开始签到
用户[1040761334]签到失败：token无效

开始领取任务奖励
用户[1040761334]完成【打开APP】失败：今日任务已经完成
用户[1040761334]完成【分享1篇文章】获得10青豆
用户[1040761334]完成【时段奖励】获得7青豆
用户[1040761334]完成【额外分享奖励】获得38青豆
用户[1040761334]完成【启动极速版】失败：此任务尚未完成
用户[1040761334]完成【阅读5篇文章】失败：此任务尚未完成
用户[1040761334]完成【分享3篇内容】失败：此任务尚未完成
用户[1040761334]完成【阅读10分钟】失败：此任务尚未完成
用户[1040761334]完成【阅读2分钟】失败：此任务尚未完成
用户[1040761334]完成【阅读20分钟】失败：此任务尚未完成
用户[1040761334]完成【进行1次分享】失败：此任务尚未完成
用户[1040761334]完成【清晨分享】失败：此任务尚未完成
用户[1040761334]完成【午间分享】失败：此任务尚未完成
用户[1040761334]完成【晚间分享】失败：此任务尚未完成
用户[1040761334]完成【定时宝箱】获得13青豆
用户[1040761334]完成【宝箱1号】失败：此任务尚未完成
用户[1040761334]完成【宝箱2号】失败：此任务尚未完成
用户[1040761334]完成【宝箱3号】失败：此任务尚未完成

开始查询账户
用户1 token无效

**Comment by smallfawn** [comment]
正常
