### ISSUE TITLE
最新版的鄞响，一直重复做第一个账号的任务。

### ISSUE THREAD

**Issue by lucienyida** [smallfawn/QLScriptPublic#5]
最新版的鄞响，一直重复做第一个账号的任务。
![2](https://github.com/smallfawn/QLScriptPublic/assets/96853173/3d1e3baa-b0aa-461c-9391-dda8b55e9fb9)
![1](https://github.com/smallfawn/QLScriptPublic/assets/96853173/f7907f9a-3528-450b-a62f-a61e057e0793)
![3](https://github.com/smallfawn/QLScriptPublic/assets/96853173/6f04c80e-9d45-4e24-b2d3-f295101cc23f)
![4](https://github.com/smallfawn/QLScriptPublic/assets/96853173/80b04bcd-3550-4aad-a35d-1d9f9260a2f4)

**Comment by Huansheng1** [comment]
已更新，请测试，如不回复，三天内将关闭该issue

**Comment by lucienyida** [comment]
已测试，目前没发现BUG
