### ISSUE TITLE
瑞安问题

### ISSUE THREAD

**Issue by a1564471347** [smallfawn/QLScriptPublic#66]
增加阅读文章时间失败 🙁 了呢,原因：处理失败【Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: "3294.179226924707"】

**Comment by moliyadi007** [comment]
账号[1],App启动成功 😄 
账号[1],启动WebView成功 😄 
账号[1],Web初始化成功 😄 
账号[1],获取版本信息成功 😄 
账号[1],获取App配置成功 😄 
账号[1],登录成功 😄 
账号[1],登录初始化:失败 🙁 了呢,原因：处理失败【
### Error updating database.  Cause: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'platform' at row 1
### The error may exist in zbjt/mty/api/dao/mybatis/DeviceMapper.java (best guess)
### The error may involve zbjt.mty.api.dao.mybatis.DeviceMapper.insert-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO client_device  ( id, platform, os_version, app_version, model, identifier, anonymous_account_id, anonymous_session_id, forbidden, created_at, updated_at, daily_hot_spot_flag, local_news_flag, activity_messages_flag, nav, proposal_word_ids, tenant_id )  VALUES  ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )
### Cause: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'platform' at row 1
; Data truncation: Data too long for column 'platform' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'platform' at row 1】

**Comment by Huansheng1** [comment]
已修复，关闭本ISSUE

**Comment by Huansheng1** [comment]
> 账号[1],App启动成功 😄 账号[1],启动WebView成功 😄 账号[1],Web初始化成功 😄 账号[1],获取版本信息成功 😄 账号[1],获取App配置成功 😄 账号[1],登录成功 😄 账号[1],登录初始化:失败 🙁 了呢,原因：处理失败【
> 
> ### Error updating database. Cause: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'platform' at row 1
> ### The error may exist in zbjt/mty/api/dao/mybatis/DeviceMapper.java (best guess)
> ### The error may involve zbjt.mty.api.dao.mybatis.DeviceMapper.insert-Inline
> ### The error occurred while setting parameters
> ### SQL: INSERT INTO client_device ( id, platform, os_version, app_version, model, identifier, anonymous_account_id, anonymous_session_id, forbidden, created_at, updated_at, daily_hot_spot_flag, local_news_flag, activity_messages_flag, nav, proposal_word_ids, tenant_id ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )
> ### Cause: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'platform' at row 1
> ; Data truncation: Data too long for column 'platform' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'platform' at row 1】

账号或者配置问题，自己检查，是否是SessionId和AccountId反了，具体看脚本说明
