### ISSUE TITLE
海尔智家签到

### ISSUE THREAD

**Issue by milletbig** [smallfawn/QLScriptPublic#7]
1. ios版本抓包没有https://mps.haiersmarthomes.com/api-gw这个域名
2. 使用了uos.haier.net/osvcm域名下的clientId和accessToken，脚本显示签到成功，但是并未真实签到成功。

**Comment by smallfawn** [comment]
截图看看

**Comment by milletbig** [comment]
![image](https://github.com/smallfawn/QLScriptPublic/assets/33082048/a30631b8-838c-4f5b-af10-c371edf1d951)![image](https://github.com/smallfawn/QLScriptPublic/assets/33082048/47eab826-1bd6-4d28-bc7c-b09385a0f6af)

**Comment by milletbig** [comment]
实际并没有签到

**Comment by faintout** [comment]
CK过期太快了

**Comment by milletbig** [comment]
抱歉，是我自己的问题，我点击错了入口，所以没有获取正确的抓包地址，现已找到。十分抱歉。另外，请问 我的-每日签到 可以增加一下吗？
