### ISSUE TITLE
立白

### ISSUE THREAD

**Issue by wang-st** [smallfawn/QLScriptPublic#76]
![image](https://github.com/smallfawn/QLScriptPublic/assets/42262535/a2faa403-f68f-4a4d-a855-c0c77325bfdb)
立白异常

**Comment by 3238614968** [comment]
数据填错了吧，新旧账号均正常
![image](https://github.com/smallfawn/QLScriptPublic/assets/88702174/4eab7d1d-e1df-419b-9038-a31da49ad009)
![image](https://github.com/smallfawn/QLScriptPublic/assets/88702174/358663e0-7a04-4c3a-b57a-c711b1f912dd)
