### ISSUE TITLE
金彩云app 二十天左右就可以兑换一箱牛奶

### ISSUE THREAD

**Issue by CC13594759** [smallfawn/QLScriptPublic#99]
金彩云app   二十天左右就可以兑换一箱牛奶
![1F717BE2F71E170BD22DEA010F91E042](https://github.com/smallfawn/QLScriptPublic/assets/59593391/7bf31835-1ca7-45a3-bcc3-2703e8d46f64)

**Comment by smallfawn** [comment]
收到

**Comment by smallfawn** [comment]
每天任务就6个豆...20天120豆怎么玩

**Comment by smallfawn** [comment]
一个月1000金豆....20天怎么换呢
